### ISSUE TITLE
Model code error

### ISSUE THREAD

**Issue by Yimi81** [lyuchenyang/Macaw-LLM#10]
[modeling.py 986 line](https://github.com/lyuchenyang/Macaw-LLM/blob/main/modeling.py#L986) and [modeling.py 1004 line](https://github.com/lyuchenyang/Macaw-LLM/blob/main/modeling.py#L1004 ) also use `video_align_attention`. Is this an error? Should we use the corresponding `audio_align_attention `and `image_align_attention`

**Comment by lyuchenyang** [comment]
Hi, thanks for pointing it out. It is a typo, we have fixed it.
