### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by gokul-uf** [lyuchenyang/Macaw-LLM#11]
Hello,
Thanks for sharing this work.

But the repo seems to be missing a LICENSE file and hence makes it difficult for people to decide if they can use this project in their work or not.

Has a decision regarding licensing been made?

Thanks!

**Comment by gokul-uf** [comment]
Only reference is to a CC By 4.0 license in the tags 
<img width="186" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/5398125/8063d800-8c4c-4f76-ac34-224037bb1e3a"> but would be great to add the license text as well

**Comment by lyuchenyang** [comment]
Hi, thanks for your interests and suggestion! We will add a license file as soon as possible
