### ISSUE TITLE
Question about finetuning all parameters of LLM?

### ISSUE THREAD

**Issue by shufangxun** [lyuchenyang/Macaw-LLM#12]
Hello, I found that you propose a one-step instruction fine-tuning approach on all parameters of LLM. Will this cause catastrophic forgetting or Overfitting on the instruction dataset ？

**Comment by lyuchenyang** [comment]
Thanks for your insightsful comments. Yes, it could introduce such problems for LLMs, we are currently investigating such problems with our system.
