### ISSUE TITLE
which llama tokenizer to use?

### ISSUE THREAD

**Issue by chatsci** [lyuchenyang/Macaw-LLM#15]
In the preprocessing file, we have tokenizer = AutoTokenizer.from_pretrained('trained_models/llama_tokenizer'). This seems won't get the llama tokenizer from HF. which llama tokenizer we should use? As there are several versions on HF. Thanks.

**Comment by lyuchenyang** [comment]
Hi, sorry for the confusion of the LLaMA tokenizer. We use the LLaMA model and tokenizer from this link: `https://huggingface.co/decapoda-research/llama-7b-hf`.
