### ISSUE TITLE
How many GPU memory needed to finetune the model?

### ISSUE THREAD

**Issue by aixiaodewugege** [lyuchenyang/Macaw-LLM#17]
Can I finetune it with my dataset with 4 * 3090?

**Comment by lyuchenyang** [comment]
Hi, based on what I estimated and other poeple's feedback, I think you can run it on 4 Nvidia 3090 GPUs with FP16 - its just the speed can be slow as Nvidia 3090 only as 24GB VRAM so you must use a smaller batch size .
