### ISSUE TITLE
What is the pad ID for tokenizer?

### ISSUE THREAD

**Issue by chatsci** [lyuchenyang/Macaw-LLM#19]
In the trainer file, I saw:

special_tokens = {
    '<image>': 32000,
    '</image>': 32001,
    '<audio>': 32002,
    '</audio>': 32003,
    '<video>': 32004,
    '</video>': 32005,
}

But in the preprocessing files, I didn't see these tokens are setted. Instead, I tried to print out the token ids, and found that it seems the PAD token id is 32000. What is the potential problem? What is the pad_id for tokenizer?

**Comment by lyuchenyang** [comment]
Hi, sorry for the late reply as I'm working on finalizing my PhD. The PAD token id depends on the vocab size of the employed tokenizer. The `special_tokens` variable is no longer used anymore, you can jusdt ignore it. Please check the preprocessing script (i.e. line 220 - 232 in `preprocess_data_unsupervised.py` ).
