### ISSUE TITLE
missing file ”data/all_visual_names.json“

### ISSUE THREAD

**Issue by wanghao-cst** [lyuchenyang/Macaw-LLM#3]
hi, thank you for making such great work open source.
However, I have encountered some issues:
1. When I run inference.sh, there is a file missing error on 'data/all_visual_names.json', how can I get this file?
2. Is there trained models we can do inference directly?
<img width="409" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/11d7d685-ae60-4484-b8a3-f283dcd01fef">

**Comment by lyuchenyang** [comment]
Hi, thanks for your interests in our work.  Regarding your questions:
    1. Please follow the steps in data preprocessing part: `python preprocess_data_supervised.py` to generate `all_visual_names.json` and other necessary datasets.
    2. We will release the model weights as soon as possible, stay tuned for more updates!

Thanks

**Comment by saransh03sharma** [comment]
> hi, thank you for making such great work open source. However, I have encountered some issues:
> 
> 1. When I run inference.sh, there is a file missing error on 'data/all_visual_names.json', how can I get this file?
> 2. Is there trained models we can do inference directly?
> 
> <img alt="image" width="409" src="https://private-user-images.githubusercontent.com/55015183/242546318-11d7d685-ae60-4484-b8a3-f283dcd01fef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDU3MTEsIm5iZiI6MTcxNjA0NTQxMSwicGF0aCI6Ii81NTAxNTE4My8yNDI1NDYzMTgtMTFkN2Q2ODUtYWU2MC00NDg0LWI4YTMtZjI4M2RjZDAxZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE1MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNzFlMDNjYTkyZDkwMjI5NGUyOTQ2OTU5YzQyYWIzMzdjM2YxZWNiZWUwNTk4NGY3NWMwMDBjZTkzOTgwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IGMuZ64JZURVgFliuNp1aPNhDRcBcHtWqp_Mmm6w1LY">

did you get to know how to use pre-trained model for inferencing purpose only?
