### ISSUE TITLE
missing file 'data/avsd/avsd_train.json'

### ISSUE THREAD

**Issue by wanghao-cst** [lyuchenyang/Macaw-LLM#4]
Hi, may I know what are these two files in preprocess_data_supervised.py?
Could you please share these files?

<img width="359" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/4d46c390-cc7c-4055-9888-2b4f91a9eb10">

**Comment by wanghao-cst** [comment]
In addition, I am not sure about these two files:

**Comment by lyuchenyang** [comment]
Hi,

Really sorry for the late reply due to my personal reasons. Regarding your questions, you can download the metadata `avsd_train.json` and `avsd_val.json` for AVSD dataset in `https://video-dialog.com/`. For VQA dataset, you can directly download them from `https://cocodataset.org/#download`, just nevermind the `added_path` postfix.

Thanks,
Chenyang

**Comment by wanghao-cst** [comment]
> Hi,
> 
> Really sorry for the late reply due to my personal reasons. Regarding your questions, you can download the metadata `avsd_train.json` and `avsd_val.json` for AVSD dataset in `https://video-dialog.com/`. For VQA dataset, you can directly download them from `https://cocodataset.org/#download`, just nevermind the `added_path` postfix.
> 
> Thanks, Chenyang

Hi, I have downloaded coco dataset, but there is no file concerning  "OpenEnded_mscoco_train2014_questions", could you please share it to us?
<img width="785" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/6f48f7fe-e0fd-47d3-97ae-21ba569f19c1">

**Comment by lyuchenyang** [comment]
You can download the questions from `https://visualqa.org/download.html`.

**Comment by wanghao-cst** [comment]
> You can download the questions from `https://visualqa.org/download.html`.

Thank you!

**Comment by lyuchenyang** [comment]
This is the data generated by ourselves, we will release them as soon as possible - no worries you can just use the supervised dataset.
