### ISSUE TITLE
Missing file "data_alp_hf.json"

### ISSUE THREAD

**Issue by wanghao-cst** [lyuchenyang/Macaw-LLM#5]
Hi, there is an unknow config file in train.sh 
Could you please share it to us?
<img width="653" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/b8f5b09a-4b30-4746-8f95-57becc5f2cfd">

**Comment by lyuchenyang** [comment]
Sorry for the confusion, `train.sh` has been corrected to be able to use the training dataset generated by preprocessing scripts.

**Comment by wanghao-cst** [comment]
> Sorry for the confusion, `train.sh` has been corrected to be able to use the training dataset generated by preprocessing scripts.

Hi, may I know how to get these two files?
![image](https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/cc7c9e21-d36d-434b-aeb0-c29e085bf9a3)
