### ISSUE TITLE
Question about setting pad token

### ISSUE THREAD

**Issue by wanghao-cst** [lyuchenyang/Macaw-LLM#6]
Hi, may I know how to set the pad token?
In the previous version of code, it was set as [32006]. I checked that in LLaMA token files, 32006 isnot used yet. Can I use any num not used before?
<img width="200" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/96f3cd41-78c5-413d-b9a0-a6792bc0244e">

<img width="392" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/3d9fa7da-eb6d-4a15-aedd-385aceb6d163">

**Comment by wanghao-cst** [comment]
<img width="1003" alt="image" src="https://github.com/lyuchenyang/Macaw-LLM/assets/55015183/08b6171c-1492-4f17-9403-8e98e5e1f342">
The original [PAD] is not working, it will raise an error when converting None to torch.int.

**Comment by lyuchenyang** [comment]
Hi, sorry for the confusion. I have refactored the preprocessing code - you can see the latest version of `preprocess_data_supervised.py` and `preprocess_data_unsupervised.py` where the special tokens will be added into the tokenizer.
