### ISSUE TITLE
Resource problem?

### ISSUE THREAD

**Issue by ghost** [lyuchenyang/Macaw-LLM#7]
I wonder with 3 big models like CLIP, LLama, Whisper, at least how much VRAM will we need to host a demo? Is it possible to host them on a single 4090 GPU?

**Comment by lyuchenyang** [comment]
Hi, LLaMA has 7B parameters while CLIP-base and Whisper-base have less than 1B parameters so based on my experiences running these models for inference, they should use around 12G VRAM with FP16 (I haven't tried FP32).  It is possible to run it on a 4090 GPU.
