### ISSUE TITLE
GPU Memory Requirement

### ISSUE THREAD

**Issue by Mak-up** [lyuchenyang/Macaw-LLM#9]
Thank you for your awesome work! I would like to know how much GPU memory at least can run on this project, can It run on a 2*3090 GPU?

**Comment by wanghao-cst** [comment]
> Thank you for your awesome work! I would like to know how much GPU memory at least can run on this project, can It run on a 2*3090 GPU?

It works for me~

**Comment by lyuchenyang** [comment]
Hi, thanks for yor interests. I think the model can fit in two 3090 GPU (2 * 24GB VRAM) with FP16.
